# Generated by Django 5.2.7 on 2025-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_day', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('students', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
